### ISSUE TITLE
Any sentence containing the word `help` anywhere will call the Help Command

### ISSUE THREAD

**Issue by eldios** [shomali11/slacker#40] opened 2019-03-12 01:36 UTC
Hi,
I'm having some issues with the Help Command specification.

Currently using in my code Slacker Git revision: 37d2f0fd93e4c63a1afaba092dc5bb548620fcb3

Specifically I set a command to be something like:
```go
	// function tied to sentences sent to the Bot and starting with "open emergency" followed by some text
	emergencyCmdDefinition := &slacker.CommandDefinition{
		Description: "Open an EMERGENCY incident to Customer Support",
		Handler: func(request slacker.Request, response slacker.ResponseWriter) {
			if err := Emergency(request, response, config); err != nil {
				Err(err.Error())
				return
			}
		},
	}
	bot.Command("open emergency <msg>", emergencyCmdDefinition)
```
and then added the Help function as:
```go
	// set the "help" message handling function
	helpCmdDefinition := &slacker.CommandDefinition{
		Description: "Help function",
		Handler: func(request slacker.Request, response slacker.ResponseWriter) {
			help(response, config)
		},
	}
	bot.Help(helpCmdDefinition)
```

But any sentence that contains the `help` word will trigger the Help Command (I guess because that's parsed earlier from what I read in your code).

Say that you write `open emergency my printer is on fire... I need some help!` that would still just print the `help` instead of triggering the `open emergency` command as it normally would.

I'd just want the `help` command to be triggered when the ONLY word is "help"... otherwise IMO the rest of the parsing should happen (go through normal commands parsing and then hit the DefaultCommand).

You can see the full code here: https://github.com/gravitational/slackbot/blob/master/slackbot.go#L74

**Comment by shomali11** [comment] 2019-03-12 03:06
The default behavior of the `commander` library that this framework relies on is to look for any mention of the command in a sentence.

I will look into seeing if we can make it an option whether to match the command "exactly" or not.

**Comment by shomali11** [comment] 2019-03-12 17:08
I updated the `commander` library to do exact matches and updated the dependencies in `slacker`.
Could you pull latest and check your case?

**Comment by eldios** [comment] 2019-03-12 17:29
using https://github.com/shomali11/slacker/commit/0d86a8f2f8f4cd263d58d9e35c96516013685ed6 didn't seem to help in my tests :thinking:

**Comment by shomali11** [comment] 2019-03-12 17:32
Strange, because I tested for it here https://github.com/shomali11/commander/blob/master/commander_test.go#L118

**Comment by eldios** [comment] 2019-03-12 17:35
Maybe the difference is that you used the function NewCommand() while I used the Help() one?

**Comment by shomali11** [comment] 2019-03-12 17:39
They internally will use the same logic. The problem with exact matches is that they will only work for direct conversations with the bot and fail when mentioning the bot in a channel.

Let me try to rework it and see how I can solve this problem for both cases.

**Comment by herwonowr** [comment] 2019-12-24 12:26
Is there any update?

**Comment by yulrizka** [comment] 2021-09-02 16:09
another idea would be to expose the default help command. so we override the default help command and still be able to call the original command from there

**Comment by arusso** [comment] 2021-12-12 23:24
> another idea would be to expose the default help command. so we override the default help command and still be able to call the original command from there

I believe [this](https://github.com/shomali11/slacker/blob/master/slacker.go#L134) is what you're looking for. The default command can be referenced within your override by calling `s.defaultHelp(...)`.

**Comment by arusso** [comment] 2021-12-13 01:53
> > another idea would be to expose the default help command. so we override the default help command and still be able to call the original command from there
> 
> 
> 
> I believe [this](https://github.com/shomali11/slacker/blob/master/slacker.go#L134) is what you're looking for. The default command can be referenced within your override by calling `s.defaultHelp(...)`.

Actually, I realize now what you're saying and you're right, the default Help command isn't available to a CommandDefinition.

I see no harm exporting the default help command so it's callable by overrides.

**Comment by arusso** [comment] 2021-12-13 05:39
Exposing defaultHelp wasn't as straightforward as I hoped so I attempted to reproduce the original issue and could not. It seems this was probably fixed at some point.

Unless another example can be provided that reproduces this issue, I'll go ahead and close this issue.

**Closed** 2022-05-31 05:16 UTC
